version: '3'
services:
  eventstore:
    image: eventstore/eventstore:20.10.0-buster-slim
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
